### ISSUE TITLE
Add name folder param

### ISSUE THREAD

**Issue by Rysakov1986** [mathec-x/express-file-based#2]
Please add name folder so param.

ex:
/routes/user/[id]/posts → /users/:id/posts  // dynamic req.params.id

and add priority for route

ex https://github.com/jesseditson/fs-router: 

// all routes are sorted by this property - the higher numbers are matched first.
// kind of like a z-index for your routes.
// note that equal priority will just sort based on the fs in the case of a collision, which is not guaranteed order on OSX/Linux
module.exports.priority = -1

**Comment by mathec-x** [comment]
featured v0.1.2
